### PR TITLE
Add detailed documentation to README

### PR DESCRIPTION
**Pull request by jeancochrane**
# Overview

This PR adds detailed documentation to the project's README, covering basic concepts, installation, API usage, and development/testing.

## Notes

- Best viewed as a formatted document [on GitHub](https://github.com/azavea/grout/blob/feature/documentation/README.md).
- The API documentation was adapted from the [DRIVER API documentation](https://github.com/WorldBank-Transport/DRIVER/blob/master/doc/api-documentation.md). The Concepts section was adapted from [my draft blog post](https://docs.google.com/document/d/1vslZLFpEJz0azjz5WBE4iPZPbtbETvSeXBDx5xeSgQw/edit?usp=sharing).

## Related issues

- Closes https://github.com/azavea/grout-2018-fellowship/issues/52.
- Closes https://github.com/azavea/grout-2018-fellowship/issues/17.

### CODE REVIEW

**Review by ddohler — APPROVED** [review]
This is really outstanding, thanks for putting this together! One thought I had is that we've found pull request templates to be a good way to gently prod developers to do things like update READMEs and CHANGELOGs; it might make sense to include a PR template with a checklist item that says something like `[ ] I've checked whether my changes affect the README and updated it if so`. What do you think?

**Comment by jeancochrane** [comment]
Great idea @ddohler! I'll add a quick PR template.

**Comment by jeancochrane** [comment]
@ddohler per our conversation today, I added the ADRs from https://github.com/azavea/grout-2018-fellowship into this repo under the `docs` directory. I also added a [Roadmap document](https://github.com/azavea/grout/blob/375debd17a5cd7505dd399fbd662f6f56cbec942/docs/roadmap.md) summarizing some of the thoughts that came out of our meeting. Let me know what you think!

**Review by ddohler — APPROVED** [review]
Looks good! The only suggestion I have is to make the ADR filenames include the ADR number somewhere, so that the chronological ordering is easier to see.

**Comment by ddohler** [comment]
Merging this so we can cut a 2.0.0 release.

**Pull request merged**
